fix: add FTP extension to Dockerfile for Shoutbomb integration

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -13,7 +13,7 @@ RUN apt-get update \
 && docker-php-ext-install pdo_dblib \
 # Install other PHP extensions
 && docker-php-ext-configure zip \
-&& docker-php-ext-install zip mysqli pdo_mysql intl \
+&& docker-php-ext-install zip mysqli pdo_mysql intl ftp \
 && a2enmod rewrite \
 && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-enabled/000-default.conf \
 && mv /var/www/html /var/www/public \
@@ -21,5 +21,5 @@ RUN apt-get update \
 | php -- --install-dir=/usr/local/bin --filename=composer \
 && echo 'AllowEncodedSlashes On' >> /etc/apache2/apache2.conf
 
-# Verify pdo_dblib is installed
-RUN php -m | grep pdo_dblib || echo "Warning: pdo_dblib not found"
+# Verify extensions are installed
+RUN php -m | grep -E "pdo_dblib|ftp" || echo "Warning: Required extensions not found"
