fix: add FTP extension to Dockerfile for Shoutbomb integration

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -8,8 +8,11 @@ RUN apt-get update && \
     apt-get install -y nodejs libicu-dev && \
     apt-get install -y zlib1g-dev mysql-client-* libzip-dev zip nano && \
     apt-get install -y freetds-dev freetds-bin freetds-common && \
+    apt-get install -y libc-client-dev libkrb5-dev && \
     docker-php-ext-configure pdo_dblib --with-libdir=/lib/x86_64-linux-gnu && \
     docker-php-ext-install pdo_dblib && \
+    docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
+    docker-php-ext-install imap && \
     docker-php-ext-configure zip && \
     docker-php-ext-install zip mysqli pdo_mysql intl ftp && \
     a2enmod rewrite && \
@@ -18,4 +21,4 @@ RUN apt-get update && \
     curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
     echo 'AllowEncodedSlashes On' >> /etc/apache2/apache2.conf
 
-RUN php -m | grep -E "pdo_dblib|ftp" || echo "Warning: Required extensions not found"
+RUN php -m | grep -E "pdo_dblib|ftp|imap" || echo "Warning: Required extensions not found"
